'use client'

import { useCallback, useEffect, useState } from 'react'
import { useTranslations } from 'next-intl'
import { useRouter } from '@/i18n/navigation'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { Separator } from '@/components/ui/separator'
import { Button } from '@/components/ui/button'
import { TimetableWithTabs } from '@/components/calendar/prototype-calendar-view'
import type { TopTabItem, TimelineBarItem } from '@/components/calendar/prototype-calendar-view'
import { useOrg } from '@/components/providers/org-provider'
import { useTimetableStore } from '@/stores/timetable-store'

const TABS: TopTabItem[] = [
  { id: 'schedule', label: 'Schedule', icon: 'calendar' },
  { id: 'clients', label: 'Clients', icon: 'client' },
]

function toDateString(d: Date) {
  return d.toISOString().slice(0, 10)
}

function formatDisplayDate(d: Date) {
  const today = new Date()
  const yesterday = new Date()
  yesterday.setDate(today.getDate() - 1)
  const tomorrow = new Date()
  tomorrow.setDate(today.getDate() + 1)

  if (toDateString(d) === toDateString(today)) return 'Today'
  if (toDateString(d) === toDateString(yesterday)) return 'Yesterday'
  if (toDateString(d) === toDateString(tomorrow)) return 'Tomorrow'

  return d.toLocaleDateString(undefined, {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  })
}

function getCurrentTimeInfo() {
  const now = new Date()
  const hours = now.getHours()
  const minutes = now.getMinutes()
  return {
    label: `${hours}:${minutes.toString().padStart(2, '0')}`,
    minute: hours * 60 + minutes,
  }
}

export default function DashboardPage() {
  const t = useTranslations('dashboard')
  const router = useRouter()
  const { org, allStaff } = useOrg()
  const { bars, setBars, loadBars } = useTimetableStore()
  const [activeTab, setActiveTab] = useState('schedule')
  const [selectedDate, setSelectedDate] = useState(() => new Date())
  const currentTime = getCurrentTimeInfo()
  const isToday = toDateString(selectedDate) === toDateString(new Date())

  const loadForDate = useCallback(
    (date: Date) => {
      loadBars(org.id, toDateString(date))
    },
    [org.id, loadBars]
  )

  useEffect(() => {
    loadForDate(selectedDate)
  }, [selectedDate, loadForDate])

  const goDay = (offset: number) => {
    setSelectedDate((prev) => {
      const next = new Date(prev)
      next.setDate(next.getDate() + offset)
      return next
    })
  }

  const goToday = () => setSelectedDate(new Date())

  const handleBarClick = (bar: TimelineBarItem) => {
    if (bar.type === 'processing' || bar.type === 'recording') return
    router.push(`/karute/${bar.id}` as Parameters<typeof router.push>[0])
  }

  const timelineStaff = allStaff.map((s) => ({
    id: s.id,
    name: s.name,
    avatarInitials: s.initials,
  }))

  const statsCards = [
    {
      label: t('customersServed'),
      value: 2,
      bg: 'bg-[#7d9ea7]',
    },
    {
      label: t('recordingsThisWeek'),
      value: 2,
      bg: 'bg-[#c4888e]',
    },
    {
      label: t('karuteGenerated'),
      value: 2,
      bg: 'bg-[#5a9a6e]',
    },
  ]

  const recentActivity = [
    { time: '14:30', text: t('mockActivity.updatedKarute') },
    { time: '13:15', text: t('mockActivity.registeredCustomer') },
    { time: '11:00', text: t('mockActivity.autoGenerated') },
    { time: '09:45', text: t('mockActivity.reminderSent') },
    { time: t('yesterday'), text: t('mockActivity.reportGenerated') },
  ]

  return (
    <div className="space-y-6">
      {/* Date Navigation */}
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon-sm" onClick={() => goDay(-1)}>
          <ChevronLeft className="size-5" />
        </Button>
        <button
          onClick={goToday}
          className="min-w-[120px] text-center text-sm font-semibold hover:text-foreground/70 transition-colors"
        >
          {formatDisplayDate(selectedDate)}
        </button>
        <Button variant="ghost" size="icon-sm" onClick={() => goDay(1)}>
          <ChevronRight className="size-5" />
        </Button>
        {!isToday && (
          <Button variant="outline" size="xs" onClick={goToday}>
            Today
          </Button>
        )}
      </div>

      {/* Timetable */}
      <div className="h-[420px]">
        <TimetableWithTabs
          tabs={TABS}
          activeTabId={activeTab}
          onTabChange={setActiveTab}
          staff={timelineStaff}
          bars={bars}
          onBarsChange={setBars}
          startHour={8}
          endHour={24}
          currentTimeLabel={isToday ? currentTime.label : undefined}
          currentMinute={isToday ? currentTime.minute : undefined}
          onBarClick={handleBarClick}
        />
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-3 gap-4">
        {statsCards.map((stat) => (
          <div
            key={stat.label}
            className={`${stat.bg} flex flex-col items-center justify-center rounded-xl px-6 py-6 text-white shadow-md transition-shadow hover:shadow-lg`}
          >
            <p className="text-lg font-bold">{stat.label}</p>
            <p className="mt-1 text-4xl font-extrabold tabular-nums">
              {stat.value}
            </p>
          </div>
        ))}
      </div>

      <Separator />

      {/* Recent Activity */}
      <div>
        <h2 className="mb-4 text-lg font-semibold">{t('recentActivity')}</h2>
        <div className="space-y-3">
          {recentActivity.map((item, i) => (
            <div
              key={i}
              className="flex items-start gap-4 rounded-lg border border-transparent px-3 py-2.5 text-sm transition-colors hover:border-border hover:bg-muted/40"
            >
              <span className="mt-0.5 min-w-[3.5rem] text-xs text-muted-foreground">
                {item.time}
              </span>
              <span className="text-foreground/90">{item.text}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
