'use client'

import { useEffect, useState } from 'react'
import { useTranslations } from 'next-intl'
import { useRouter } from '@/i18n/navigation'
import { Separator } from '@/components/ui/separator'
import { TimetableWithTabs } from '@/components/calendar/prototype-calendar-view'
import type { TopTabItem, TimelineBarItem } from '@/components/calendar/prototype-calendar-view'
import { useOrg } from '@/components/providers/org-provider'
import { useTimetableStore } from '@/stores/timetable-store'

const TABS: TopTabItem[] = [
  { id: 'schedule', label: 'Schedule', icon: 'calendar' },
  { id: 'clients', label: 'Clients', icon: 'client' },
]

function getCurrentTimeInfo() {
  const now = new Date()
  const hours = now.getHours()
  const minutes = now.getMinutes()
  return {
    label: `${hours}:${minutes.toString().padStart(2, '0')}`,
    minute: hours * 60 + minutes,
  }
}

export default function DashboardPage() {
  const t = useTranslations('dashboard')
  const router = useRouter()
  const { org, allStaff } = useOrg()
  const { bars, setBars, loadBars, loaded } = useTimetableStore()
  const [activeTab, setActiveTab] = useState('schedule')
  const currentTime = getCurrentTimeInfo()

  useEffect(() => {
    if (!loaded) loadBars(org.id)
  }, [org.id, loaded, loadBars])

  const handleBarClick = (bar: TimelineBarItem) => {
    if (bar.type === 'processing' || bar.type === 'recording') return
    router.push(`/karute/${bar.id}` as Parameters<typeof router.push>[0])
  }

  const timelineStaff = allStaff.map((s) => ({
    id: s.id,
    name: s.name,
    avatarInitials: s.initials,
  }))

  const statsCards = [
    {
      label: t('customersServed'),
      value: 2,
      bg: 'bg-[#7d9ea7]',
    },
    {
      label: t('recordingsThisWeek'),
      value: 2,
      bg: 'bg-[#c4888e]',
    },
    {
      label: t('karuteGenerated'),
      value: 2,
      bg: 'bg-[#5a9a6e]',
    },
  ]

  const recentActivity = [
    { time: '14:30', text: t('mockActivity.updatedKarute') },
    { time: '13:15', text: t('mockActivity.registeredCustomer') },
    { time: '11:00', text: t('mockActivity.autoGenerated') },
    { time: '09:45', text: t('mockActivity.reminderSent') },
    { time: t('yesterday'), text: t('mockActivity.reportGenerated') },
  ]

  return (
    <div className="space-y-6">
      {/* Timetable */}
      <div className="h-[420px]">
        <TimetableWithTabs
          tabs={TABS}
          activeTabId={activeTab}
          onTabChange={setActiveTab}
          staff={timelineStaff}
          bars={bars}
          onBarsChange={setBars}
          startHour={8}
          endHour={24}
          currentTimeLabel={currentTime.label}
          currentMinute={currentTime.minute}
          onBarClick={handleBarClick}
        />
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-3 gap-4">
        {statsCards.map((stat) => (
          <div
            key={stat.label}
            className={`${stat.bg} flex flex-col items-center justify-center rounded-xl px-6 py-6 text-white shadow-md transition-shadow hover:shadow-lg`}
          >
            <p className="text-lg font-bold">{stat.label}</p>
            <p className="mt-1 text-4xl font-extrabold tabular-nums">
              {stat.value}
            </p>
          </div>
        ))}
      </div>

      <Separator />

      {/* Recent Activity */}
      <div>
        <h2 className="mb-4 text-lg font-semibold">{t('recentActivity')}</h2>
        <div className="space-y-3">
          {recentActivity.map((item, i) => (
            <div
              key={i}
              className="flex items-start gap-4 rounded-lg border border-transparent px-3 py-2.5 text-sm transition-colors hover:border-border hover:bg-muted/40"
            >
              <span className="mt-0.5 min-w-[3.5rem] text-xs text-muted-foreground">
                {item.time}
              </span>
              <span className="text-foreground/90">{item.text}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
